#!/usr/bin/env bash
set -euo pipefail

# This script produces a JSON matrix with top-level changed folders (excludes
# .github and docs) when run as part of GitHub Actions for pull requests, 
# merges, and published releases on `main`.

### ENV is generated by the GitHub Actions env: settings 
## For pull_request triggers, the following are set
# DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
# BASE_SHA: ${{ github.event.pull_request.base.sha }}
# HEAD_SHA: ${{ github.event.pull_request.head.sha }}
# ACTION: ${{ github.event.action }}

## For push triggers (e.g., merge a PR to main), the following are set
# DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
# BASE_SHA: ${{ github.event.before }}
# HEAD_SHA: ${{ github.event.after }}
# ACTION: ${{ github.event_name }} (note that we use event_name, not event.action 
#                                   here since there is no action key in the 
#                                   event payload for a "push")

## For release triggers (e.g., tag a release on main), the following are set
# DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
# HEAD_SHA: ${{ github.event.after }}
# ACTION: ${{ github.event.action }}

# By default, the "release" trigger does NOT set BASE_SHA in the environment. 
# Our workflow gracefully handles this by setting that value (if it exists) and
# setting a FIRST_RELEASE boolean so that we can gracefully handle the first 
# tagged release that will not have a BASE_SHA value.

# The only time FIRST_RELEASE is "true" is for the very first tagged release
# on the `main` branch. We generate an empty "paths" list in the JSON output
# and then exit the script.
if [ "${FIRST_RELEASE:-false}" == "true" ]; then
  echo "--first release: nothing to deploy--"
  JSON='{"paths":[]}'
  if [ -n "${GITHUB_OUTPUT:-}" ]; then
    echo "matrix<<EOF" >> "$GITHUB_OUTPUT"
    echo "$JSON" >> "$GITHUB_OUTPUT"
    echo "EOF" >> "$GITHUB_OUTPUT"
  fi
  echo "$JSON"
  exit 0
fi

# Check if this is running as a local test (and if it is, use an
# isolated work directory for the `main` branch)
if [ "${LOCAL_TEST:-}" == "true" ]; then
    echo "--test tagged release in special working directory--"
    BASE_SHA=$(git -C "${WORK_DIR}" rev-parse $(git -C "${WORK_DIR}" describe --tags --abbrev=0 main^))
fi

# We allow for a test "diff" to be passed to the script for local testing
if [ -n "${TEST_DIFF:-}" ]; then
  DIFF="$TEST_DIFF"
else
  DIFF=$(git diff --dirstat=files,0,cumulative "$BASE_SHA" "$HEAD_SHA" | awk -F ' ' '{print $2}' | grep -vE '(^.github|tests)' || true)
fi

# Extract top-level directories only (ignore files in repo root) and dedupe
TOP_LEVEL=$(printf "%s\n" "$DIFF" | grep '/' | awk -F/ '{print $1}' | grep -vE '^(\\.github|tests)$' | sort -u || true)

# Build JSON
JSON='{"paths":['
first=true
while IFS= read -r p; do
  [ -z "$p" ] && continue
  if [ "$first" = true ]; then
    JSON="$JSON\"$p\""
    first=false
  else
    JSON="$JSON,\"$p\""
  fi
done <<< "$TOP_LEVEL"
JSON="$JSON]}"

# Export matrix via GITHUB_OUTPUT if available (GitHub Actions); otherwise skip
if [ -n "${GITHUB_OUTPUT:-}" ]; then
  echo "matrix<<EOF" >> "$GITHUB_OUTPUT"
  echo "$JSON" >> "$GITHUB_OUTPUT"
  echo "EOF" >> "$GITHUB_OUTPUT"
fi

# Also print to logs for debugging
echo "$JSON"
